// AIVEX registration — Data Contract V4 (canonical).
//
// One module shared by the browser form, the API and the tests: versions,
// enums, limits, pure normalisers and field rules, the V4 payload validator,
// the frontend state/payload builders, the student card policy and the
// Storage path rule. See docs/aivex-data-contract-v4.md.
//
// A registration carries two classes of data:
//   OFFICIAL DATA               -> PostgreSQL, Word/PDF, admin views
//   INTERNAL VERIFICATION DATA  -> the three student card photos, and the
//                                  identity card image of the head of
//                                  delegation and of the driver: private
//                                  Storage buckets, path/mime/size/sha256 in
//                                  PostgreSQL, never printed, never public.
//
// Pure: no React, window, document, Supabase, process.env or network, so it
// runs as is in Vite, in a Vercel Function and under `node --test`. The form
// runs these rules for UX; the API always re-runs them and is the authority.
// The public reference is generated by the API only (api/_lib/aivex-reference.js).

import { OTHER_INSTITUTION_ID, findInstitution, findWilaya } from '../../src/data/algeriaHigherEducation.js'

const frozen = (list) => Object.freeze([...list])

// --- Versions -----------------------------------------------------------

export const AIVEX_FORM_VERSION = 4
// The edition registrations are open for. The browser echoes it and the API
// refuses any other value: a stale page can never file into another edition.
export const AIVEX_EDITION = 2
// Official rule: a team is EXACTLY three students.
export const AIVEX_STUDENT_COUNT = 3
export const STUDENT_POSITIONS = frozen(Array.from({ length: AIVEX_STUDENT_COUNT }, (_, index) => index + 1))

// --- Enums (values stored in the database, never UI labels) --------------

export const ACTIVITY_OFFICIAL_ROLES = frozen(['sub_director_activities', 'activities_officer'])

export const REGISTRATION_STATUSES = frozen(['submitted', 'under_review', 'approved', 'rejected', 'cancelled'])
export const DEFAULT_REGISTRATION_STATUS = 'submitted'

// inscription -> Word/PDF -> print -> signature + stamp -> upload -> admin check
export const DOCUMENT_STATUSES = frozen([
  'not_generated',
  'generating',
  'awaiting_signature',
  'signed_document_uploaded',
  'under_review',
  'changes_required',
  'validated',
  'generation_failed',
  'expired',
])
export const DEFAULT_DOCUMENT_STATUS = 'not_generated'

// --- Payload shape --------------------------------------------------------

// Every object of the payload is closed: a key outside these lists is
// refused with its path, never silently dropped.
export const V4_FIELDS = Object.freeze({
  registration: frozen([
    'submissionId', 'edition', 'formVersion', 'team', 'activityOfficial', 'delegationHead', 'driver', 'students', 'consent',
  ]),
  team: frozen(['name', 'wilaya', 'institution']),
  wilaya: frozen(['code', 'name']),
  institution: frozen(['id', 'name', 'custom']),
  activityOfficial: frozen(['role', 'fullName', 'email', 'phone']),
  person: frozen(['fullName', 'phone', 'rfid', 'idCard']),
  student: frozen(['position', 'fullName', 'phone', 'bacYear', 'rfid', 'studentCard']),
})

// Owned by the server: sending one of them is a contract violation.
export const SERVER_AUTHORITATIVE_FIELDS = frozen([
  'id', 'reference', 'status', 'registrationStatus', 'documentStatus', 'currentFormRevision', 'templateVersion',
  'submittedAt', 'source', 'createdAt', 'updatedAt',
])

// Form v3 vocabulary: refused wherever it appears, with an explicit message.
export const LEGACY_V3_FIELDS = frozen([
  'form', 'version', 'answers', 'nationalId', 'registrationNumber', 'studyLevel', 'leader', 'isLeader', 'member',
])

// Anti-bot field. The handler answers a neutral success before validation
// when it is filled, so the validator only tolerates the key (top level).
const HONEYPOT_FIELD = 'website'

export const DATA_CLASSES = Object.freeze({
  internalVerification: frozen(['students[].studentCard', 'delegationHead.idCard', 'driver.idCard']),
})

// --- Student card (INTERNAL VERIFICATION DATA) ---------------------------

export const studentCardField = (position) => `studentCard_${position}`
export const STUDENT_CARD_FIELDS = frozen(STUDENT_POSITIONS.map(studentCardField))
export const STUDENT_CARD_FIELD_PATTERN = new RegExp(`^studentCard_[1-${AIVEX_STUDENT_COUNT}]$`)

export const STUDENT_CARD_POLICY = Object.freeze({
  classification: 'internal_verification',
  required: true,
  printable: false,
  bucket: 'aivex-student-cards',
  publicBucket: false,
  maxBytes: 5 * 1024 * 1024,
  // Images only: the organisers ask for a photo of the card. PDF stays out
  // until they explicitly need it (open decision).
  types: Object.freeze({
    'image/jpeg': Object.freeze({ extension: 'jpg', extensions: frozen(['jpg', 'jpeg']), label: 'JPG' }),
    'image/png': Object.freeze({ extension: 'png', extensions: frozen(['png']), label: 'PNG' }),
    'image/webp': Object.freeze({ extension: 'webp', extensions: frozen(['webp']), label: 'WEBP' }),
  }),
  mimeAliases: Object.freeze({ 'image/jpg': 'image/jpeg', 'image/pjpeg': 'image/jpeg' }),
})

export const canonicalCardMime = (mime) => {
  const type = String(mime || '').toLowerCase()
  return STUDENT_CARD_POLICY.mimeAliases[type] || type
}

// The checks the form runs on a picked file and the API runs again on the
// received part (from the declared type and the real byte count), for ANY
// image policy (student card, identity card). Returns '' or 'missing' |
// 'type' | 'empty' | 'size'. The API then also reads the file's magic bytes,
// which a browser cannot do reliably.
export function imageFileIssue(policy, file) {
  if (!file) return 'missing'
  if (!policy.types[canonicalCardMime(file.type)]) return 'type'
  if (!(file.size > 0)) return 'empty'
  if (file.size > policy.maxBytes) return 'size'
  return ''
}

export const studentCardFileIssue = (file) => imageFileIssue(STUDENT_CARD_POLICY, file)

// Multipart file name for a card: derived from the position and type, so the
// applicant's own file name (which may contain a name) never leaves the device.
export function studentCardUploadName(position, mime) {
  const type = STUDENT_CARD_POLICY.types[canonicalCardMime(mime)]
  return type ? `${studentCardField(position)}.${type.extension}` : studentCardField(position)
}

// --- Identity cards (INTERNAL VERIFICATION DATA) --------------------------
//
// One national identity card image for the head of delegation and one for
// the driver, sent with the registration. Same class of data as the student
// cards, but kept in its OWN private bucket so that access can be granted
// (and audited) separately. Never printed, never public, never reachable
// through the candidate Magic Link.
//
// Only JPEG and PNG: the bytes are still checked server-side. The student
// cards additionally accept WEBP; identity documents deliberately do not.

// subject (key of the person in the payload) -> multipart part name.
export const IDENTITY_CARD_FIELDS_BY_SUBJECT = Object.freeze({
  delegationHead: 'delegationHeadIdCard',
  driver: 'driverIdCard',
})
export const IDENTITY_CARD_SUBJECTS = frozen(Object.keys(IDENTITY_CARD_FIELDS_BY_SUBJECT))
export const IDENTITY_CARD_FIELDS = frozen(Object.values(IDENTITY_CARD_FIELDS_BY_SUBJECT))
export const identityCardField = (subject) => IDENTITY_CARD_FIELDS_BY_SUBJECT[subject]

// Every file part of a registration request, and how many there can be.
export const REGISTRATION_FILE_FIELDS = frozen([...STUDENT_CARD_FIELDS, ...IDENTITY_CARD_FIELDS])
export const REGISTRATION_MAX_FILES = REGISTRATION_FILE_FIELDS.length
export const REGISTRATION_FILE_FIELD_PATTERN = new RegExp(`^(${REGISTRATION_FILE_FIELDS.join('|')})$`)

export const IDENTITY_CARD_POLICY = Object.freeze({
  classification: 'internal_verification',
  required: true,
  printable: false,
  bucket: 'aivex-id-cards',
  publicBucket: false,
  maxBytes: 5 * 1024 * 1024,
  types: Object.freeze({
    'image/jpeg': STUDENT_CARD_POLICY.types['image/jpeg'],
    'image/png': STUDENT_CARD_POLICY.types['image/png'],
  }),
  mimeAliases: STUDENT_CARD_POLICY.mimeAliases,
  // Folder of each subject inside the bucket path (see identityCardStoragePath).
  folders: Object.freeze({ delegationHead: 'delegation-head', driver: 'driver' }),
})

export const identityCardFileIssue = (file) => imageFileIssue(IDENTITY_CARD_POLICY, file)

// Multipart file name of an identity card: derived from the part name and the
// final type, so the applicant's own file name (often a name) never leaves the
// device.
export function identityCardUploadName(field, mime) {
  const type = IDENTITY_CARD_POLICY.types[canonicalCardMime(mime)]
  return type ? `${field}.${type.extension}` : field
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const UUID_V4_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

export const isUuidV4 = (value) => typeof value === 'string' && UUID_V4_RE.test(value)

// Deterministic private path inside the bucket, without personal data:
// edition-{edition}/{registrationId}/student-{position}.{ext}. Never a public URL.
export function studentCardStoragePath(registrationId, position, mime, edition = AIVEX_EDITION) {
  const type = STUDENT_CARD_POLICY.types[mime]
  if (typeof registrationId !== 'string' || !UUID_RE.test(registrationId)
    || !STUDENT_POSITIONS.includes(position) || !type || !Number.isInteger(edition) || edition < 1) {
    throw new TypeError('Invalid student card storage path input.')
  }
  return `edition-${edition}/${registrationId.toLowerCase()}/student-${position}.${type.extension}`
}

// Private path inside the identity card bucket, without personal data:
// edition-{edition}/{registrationId}/{delegation-head|driver}/{randomId}.{ext}
//
// Both ids are generated by the SERVER (the registration's UUID, and one fresh
// random UUID per file): nothing the client sends ever reaches a path, and
// the path cannot be guessed from the registration alone. The random id is a
// parameter so this module stays pure (no crypto import). Never a public URL.
export function identityCardStoragePath(registrationId, subject, mime, randomId, edition = AIVEX_EDITION) {
  const type = IDENTITY_CARD_POLICY.types[mime]
  const folder = IDENTITY_CARD_POLICY.folders[subject]
  if (typeof registrationId !== 'string' || !UUID_RE.test(registrationId)
    || typeof randomId !== 'string' || !UUID_RE.test(randomId)
    || !folder || !type || !Number.isInteger(edition) || edition < 1) {
    throw new TypeError('Invalid identity card storage path input.')
  }
  return `edition-${edition}/${registrationId.toLowerCase()}/${folder}/${randomId.toLowerCase()}.${type.extension}`
}

// --- Limits -------------------------------------------------------------

export const LIMITS = Object.freeze({
  teamName: frozen([2, 120]),
  customInstitution: frozen([3, 180]),
  fullName: frozen([3, 120]),
  email: 254,
  phoneInput: 40,
  // Head of delegation and driver ONLY. No RFID format has been confirmed for
  // them by the organisers, so this stays a technical bound; the student RFID
  // has its own, exact rule (STUDENT_RFID_PATTERN).
  delegationRfid: frozen([1, 64]),
  source: 500,
})

// --- Business rules of this edition ---------------------------------------
//
// Fixed on purpose. Nothing below is derived from the clock or expands by
// itself every year: when a later edition needs another range or format, this
// contract is changed deliberately (and AIVEX_EDITION with it).

// BAC year: 2019 to 2026 inclusive, for the current edition.
export const BAC_YEAR_RANGE = Object.freeze({ min: 2019, max: 2026 })

// Phone: an Algerian mobile number in its national form — exactly ten digits,
// starting with 05, 06 or 07. '+213…' is NOT an accepted alternative: it is
// never rewritten into a local number, it is refused.
export const PHONE_PATTERN = /^0[567][0-9]{8}$/

// Student RFID: exactly eight digits (an identifier, kept as text: leading
// zeros stay). The head of delegation's and the driver's RFID do NOT follow
// this rule (see LIMITS.delegationRfid).
export const STUDENT_RFID_PATTERN = /^[0-9]{8}$/

// --- Normalisers (pure, identical in the browser and on the server) -------

const CONTROL_CHARS = /\p{Cc}/gu
// Invisible formatting characters: bidirectional marks (LRM, RLM, embeddings and
// overrides), zero-width joiners, soft hyphen, BOM.
const FORMAT_CHARS = /\p{Cf}/gu

// Trimmed, NFC, control characters and runs of whitespace folded to one space.
export const normalizeText = (value) => (typeof value === 'string'
  ? value.normalize('NFC').replace(CONTROL_CHARS, ' ').replace(/\s+/g, ' ').trim()
  : '')

// A person's name: normalizeText, after dropping the invisible formatting
// characters that Arabic text pasted from a chat or a document often carries
// (RLM, LRM...). They change no letter, but they would make a name fail
// "letters only" for a reason the applicant cannot see, and bidirectional
// overrides can make a name display as another one. The spelling is otherwise
// untouched: never transliterated, never upper- or lower-cased.
export const normalizePersonName = (value) => normalizeText(typeof value === 'string' ? value.replace(FORMAT_CHARS, '') : value)

export const normalizeEmail = (value) => (typeof value === 'string' ? value.trim().toLowerCase() : '')

// Harmless visual separators are dropped BEFORE validating, so that the
// canonical value is what is checked and stored: '0555 12 34 56',
// '0555-12-34-56' and '0555.12.34.56' all become '0555123456'. Anything else
// stays where it is and makes the number invalid — in particular a leading
// '+' ('+213 555 12 34 56' -> '+213555123456', refused) and parentheses.
// Always a string, never a Number.
export const normalizePhone = (value) => (typeof value === 'string' ? value.trim().replace(/[\s.-]/g, '') : '')

// An RFID is an identifier, not a quantity: a string, trimmed, nothing else
// (leading zeros and case are kept as typed; inner spaces are NOT removed, so
// '1234 5678' stays invalid).
export const normalizeRfid = (value) => (typeof value === 'string' ? value.trim() : '')

// Form inputs give '2023'; the payload carries the integer 2023. Anything
// else ('BAC 2023', '2023/2024', 2023.5) becomes null and fails validation.
export function normalizeBacYear(value) {
  if (Number.isInteger(value)) return value
  if (typeof value === 'string' && /^\d{4}$/.test(value.trim())) return Number(value.trim())
  return null
}

// --- Field rules (shared by the form messages and the API validator) ------

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
// An address never legitimately holds a control or an invisible formatting
// character; one would reach PostgreSQL as text it cannot store (NUL) or hide
// in the value.
const EMAIL_UNSAFE_CHARS = /[\p{Cc}\p{Cf}]/u
const WILAYA_CODE_RE = /^(0[1-9]|[1-4][0-9]|5[0-8])$/
// Unicode-aware: any letter of any script (Latin with accents, Arabic...), with
// its combining marks (Arabic vowel signs, Latin accents that have no
// precomposed form), in words separated by single spaces. No digit, no
// punctuation (hyphen, apostrophe, dot, underscore...), no symbol, no emoji.
// A word must start with a letter, so a lone mark is not a name. Linear: the
// two classes never overlap, there is no nested ambiguity.
const PERSON_NAME_RE = /^\p{L}[\p{L}\p{M}]*(?: \p{L}[\p{L}\p{M}]*)*$/u

export const within = (text, [min, max]) => text.length >= min && text.length <= max
export const isValidEmail = (email) => email.length <= LIMITS.email && EMAIL_RE.test(email) && !EMAIL_UNSAFE_CHARS.test(email)

// A CANONICAL phone number (already through normalizePhone).
export const isValidPhone = (phone) => typeof phone === 'string' && PHONE_PATTERN.test(phone)

// Raw input (as typed) -> is it an acceptable phone number once normalised?
export const isValidPhoneInput = (value) => typeof value === 'string'
  && value.trim().length <= LIMITS.phoneInput && isValidPhone(normalizePhone(value))

// Two explicit RFID rules: a student's is exactly eight digits, the head of
// delegation's and the driver's is only bounded. Both take a trimmed string.
export const isValidStudentRfid = (rfid) => typeof rfid === 'string' && STUDENT_RFID_PATTERN.test(rfid)
export const isValidDelegationRfid = (rfid) => typeof rfid === 'string' && within(rfid, LIMITS.delegationRfid)
  && !/\p{Cc}/u.test(rfid)

// The one decision behind every person name (activity official, head of
// delegation, driver, students): '' when acceptable, else the first problem —
// 'required' (nothing left after normalising), 'chars' (something other than
// letters and spaces), 'short' or 'long' (outside 3 to 120 characters). The
// characters are checked first: '12' is not a name, whatever its length.
// The form turns the code into a translated message, the API into an English one.
export function personNameIssue(value) {
  const name = normalizePersonName(value)
  if (!name) return 'required'
  if (!PERSON_NAME_RE.test(name)) return 'chars'
  if (name.length < LIMITS.fullName[0]) return 'short'
  return name.length > LIMITS.fullName[1] ? 'long' : ''
}
export const isValidPersonName = (value) => personNameIssue(value) === ''

// BAC year, for the whole edition (BAC_YEAR_RANGE): an integer, never a string.
export const isValidBacYear = (year) => Number.isInteger(year) && year >= BAC_YEAR_RANGE.min && year <= BAC_YEAR_RANGE.max

// Years offered by the form's select, most recent first: exactly the years
// the API accepts, and no others.
export function bacYearChoices() {
  return Array.from({ length: BAC_YEAR_RANGE.max - BAC_YEAR_RANGE.min + 1 }, (_, index) => BAC_YEAR_RANGE.max - index)
}

// --- Validator (pure: no database, no Storage, no network) ---------------

const isObject = (value) => value !== null && typeof value === 'object' && !Array.isArray(value)
const pass = (value) => ({ ok: true, value })
const fail = (message, field) => ({ ok: false, status: 400, message, ...(field ? { field } : {}) })
const at = (path, key) => (path ? `${path}.${key}` : key)

function unexpectedKey(record, allowed, path) {
  for (const key of Object.keys(record)) {
    if (allowed.includes(key)) continue
    if (SERVER_AUTHORITATIVE_FIELDS.includes(key)) {
      return fail(`"${key}" is assigned by the server and must not be sent.`, at(path, key))
    }
    if (LEGACY_V3_FIELDS.includes(key)) {
      return fail(`"${key}" belongs to the old registration form and is not accepted. Please reload the page.`, at(path, key))
    }
    return fail(`Unexpected field "${key}": it is not part of AIVEX form v${AIVEX_FORM_VERSION}.`, at(path, key))
  }
  return null
}

// The stored value is the canonical ten-digit number, whatever separators were typed.
function readPhone(value, label, field) {
  return isValidPhoneInput(value)
    ? pass(normalizePhone(value))
    : fail(`${label}: the phone number must contain exactly 10 digits and start with 05, 06 or 07.`, field)
}

const NAME_PROBLEMS = {
  required: 'enter the full name.',
  chars: 'the name must contain letters and spaces only.',
  short: `enter the full name (${LIMITS.fullName[0]} to ${LIMITS.fullName[1]} characters).`,
  long: `enter the full name (${LIMITS.fullName[0]} to ${LIMITS.fullName[1]} characters).`,
}

function readFullName(value, label, field) {
  const issue = personNameIssue(value)
  return issue ? fail(`${label}: ${NAME_PROBLEMS[issue]}`, field) : pass(normalizePersonName(value))
}

// An RFID is an identifier, not a number: it arrives as text (a JSON number has
// already lost its leading zeros) and leaves as the same text. Which RFIDs are
// acceptable is decided by the caller: a student's and a delegation member's
// are two different rules.
function readRfidText(value, label, field) {
  if (value === undefined || value === null) return fail(`${label}: the RFID is required.`, field)
  if (typeof value !== 'string') return fail(`${label}: the RFID must be sent as text.`, field)
  const rfid = normalizeRfid(value)
  return rfid ? pass(rfid) : fail(`${label}: the RFID is required.`, field)
}

function readDelegationRfid(value, label, field) {
  const rfid = readRfidText(value, label, field)
  if (!rfid.ok) return rfid
  return isValidDelegationRfid(rfid.value) ? rfid : fail(`${label}: enter the RFID (${LIMITS.delegationRfid[0]} to ${LIMITS.delegationRfid[1]} characters).`, field)
}

function readStudentRfid(value, label, field) {
  const rfid = readRfidText(value, label, field)
  if (!rfid.ok) return rfid
  return isValidStudentRfid(rfid.value) ? rfid : fail(`${label}: the student RFID must contain exactly 8 digits.`, field)
}

function readTeam(raw) {
  const path = 'team'
  if (!isObject(raw)) return fail('Team: invalid data.', path)
  const extra = unexpectedKey(raw, V4_FIELDS.team, path)
  if (extra) return extra

  const name = normalizeText(raw.name)
  if (!within(name, LIMITS.teamName)) return fail('Please enter a team name (2 to 120 characters).', `${path}.name`)

  if (!isObject(raw.wilaya)) return fail('Please choose a valid wilaya.', `${path}.wilaya`)
  const wilayaExtra = unexpectedKey(raw.wilaya, V4_FIELDS.wilaya, `${path}.wilaya`)
  if (wilayaExtra) return wilayaExtra
  // Codes, ids and enum values are matched EXACTLY, never trimmed: they are
  // tokens the form takes from a list, so anything else is a crafted request.
  const code = typeof raw.wilaya.code === 'string' ? raw.wilaya.code : ''
  const wilaya = WILAYA_CODE_RE.test(code) ? findWilaya(code) : null
  if (!wilaya) return fail('Please choose a valid wilaya.', `${path}.wilaya.code`)

  const rawInstitution = raw.institution
  if (!isObject(rawInstitution)) return fail('Please choose a university or institution.', `${path}.institution`)
  const institutionExtra = unexpectedKey(rawInstitution, V4_FIELDS.institution, `${path}.institution`)
  if (institutionExtra) return institutionExtra
  if (typeof rawInstitution.custom !== 'boolean') return fail('Invalid institution data.', `${path}.institution.custom`)
  const id = typeof rawInstitution.id === 'string' ? rawInstitution.id : ''

  // A custom institution is allowed ONLY through the "other" entry, and a
  // listed one only if it belongs to the chosen wilaya: the official record
  // is always resolved here, from the dataset, never from what was sent.
  let institution
  if (rawInstitution.custom) {
    if (id !== OTHER_INSTITUTION_ID) return fail(`A custom institution must use the id "${OTHER_INSTITUTION_ID}".`, `${path}.institution.id`)
    const customName = normalizeText(rawInstitution.name)
    if (!within(customName, LIMITS.customInstitution)) {
      return fail('Please enter the institution name (3 to 180 characters).', `${path}.institution.name`)
    }
    institution = { id: OTHER_INSTITUTION_ID, name: customName, custom: true }
  } else {
    const listed = id && id !== OTHER_INSTITUTION_ID ? findInstitution(wilaya.code, id) : null
    if (!listed) return fail('Please choose a university or institution from the selected wilaya.', `${path}.institution.id`)
    // Official label from the dataset, whatever the request claimed.
    institution = { id: listed.id, name: listed.name, custom: false }
  }

  // Snapshot: the labels stored with the registration are the dataset labels
  // of the day, so old registrations stay readable if the dataset changes.
  return pass({ name, wilaya: { code: wilaya.code, name: wilaya.name }, institution })
}

function readActivityOfficial(raw) {
  const path = 'activityOfficial'
  const label = 'Activity administration contact'
  if (!isObject(raw)) return fail(`${label}: invalid data.`, path)
  const extra = unexpectedKey(raw, V4_FIELDS.activityOfficial, path)
  if (extra) return extra

  // The internal value, exactly: never a translated label, never padded.
  const role = typeof raw.role === 'string' ? raw.role : ''
  if (!ACTIVITY_OFFICIAL_ROLES.includes(role)) return fail(`${label}: choose a role.`, `${path}.role`)

  const fullName = readFullName(raw.fullName, label, `${path}.fullName`)
  if (!fullName.ok) return fullName

  // Not unique: one official may register several teams (idempotency is
  // carried by submissionId, not by this address).
  const email = normalizeEmail(raw.email)
  if (!isValidEmail(email)) return fail(`${label}: enter a valid email address.`, `${path}.email`)

  const phone = readPhone(raw.phone, label, `${path}.phone`)
  if (!phone.ok) return phone

  return pass({ role, fullName: fullName.value, email, phone: phone.value })
}

// Head of delegation and driver: same record, identified by RFID (v4 never
// collects national ID numbers). Each also names the multipart part that
// carries their identity card IMAGE; the bytes travel separately and are
// checked by api/_lib/aivex-validation-v4.js (the number is never read).
function readPerson(raw, path, label, cardField) {
  if (!isObject(raw)) return fail(`${label}: invalid data.`, path)
  const extra = unexpectedKey(raw, V4_FIELDS.person, path)
  if (extra) return extra

  const fullName = readFullName(raw.fullName, label, `${path}.fullName`)
  if (!fullName.ok) return fullName
  const phone = readPhone(raw.phone, label, `${path}.phone`)
  if (!phone.ok) return phone
  const rfid = readDelegationRfid(raw.rfid, label, `${path}.rfid`)
  if (!rfid.ok) return rfid
  if (raw.idCard !== cardField) {
    return fail(`${label}: the identity card image is required and must be sent as "${cardField}". Please reload the page.`, `${path}.idCard`)
  }

  return pass({ fullName: fullName.value, phone: phone.value, rfid: rfid.value, idCard: cardField })
}

function readStudents(raw) {
  const path = 'students'
  if (!Array.isArray(raw)) return fail('Invalid student list.', path)
  if (raw.length !== AIVEX_STUDENT_COUNT) return fail(`A team is exactly ${AIVEX_STUDENT_COUNT} students.`, path)

  const students = []
  const rfids = new Set()
  for (const [index, student] of raw.entries()) {
    const position = index + 1
    const base = `${path}[${index}]`
    const label = `Student ${position}`
    if (!isObject(student)) return fail(`${label}: invalid data.`, base)
    const extra = unexpectedKey(student, V4_FIELDS.student, base)
    if (extra) return extra

    // The integer, strictly: '1', '01', null, 0 and 4 are all refused.
    if (student.position !== position) return fail(`${label}: the position must be ${position}.`, `${base}.position`)

    const fullName = readFullName(student.fullName, label, `${base}.fullName`)
    if (!fullName.ok) return fullName
    const phone = readPhone(student.phone, label, `${base}.phone`)
    if (!phone.ok) return phone

    // The payload carries an integer: '2023', 'BAC 2023' or '2023/2024' are refused.
    if (student.bacYear === undefined || student.bacYear === null || student.bacYear === '') {
      return fail(`${label}: the BAC year is required.`, `${base}.bacYear`)
    }
    if (!isValidBacYear(student.bacYear)) {
      return fail(`${label}: the BAC year must be between ${BAC_YEAR_RANGE.min} and ${BAC_YEAR_RANGE.max}.`, `${base}.bacYear`)
    }

    const rfid = readStudentRfid(student.rfid, label, `${base}.rfid`)
    if (!rfid.ok) return rfid
    if (rfids.has(rfid.value)) return fail(`${label}: each student needs their own RFID.`, `${base}.rfid`)
    rfids.add(rfid.value)

    // The JSON only names the multipart part; the bytes travel separately.
    const cardField = studentCardField(position)
    if (student.studentCard !== cardField) return fail(`${label}: the student card must be sent as "${cardField}".`, `${base}.studentCard`)

    students.push({ position, fullName: fullName.value, phone: phone.value, bacYear: student.bacYear, rfid: rfid.value, studentCard: cardField })
  }
  return pass(students)
}

// Validates the canonical v4 payload (the `payload` multipart part). Returns
// { ok: true, value } with a clean, explicitly rebuilt structure — the only
// input the API maps to the database — or { ok: false, status: 400, message,
// field } where `field` is the payload path of the first problem.
//
// Pure and independent of the clock: every rule of the edition (BAC years,
// phone and RFID formats) is a constant of this file.
export function validateRegistrationV4(body) {
  if (!isObject(body)) return fail('Invalid registration data.')
  // A v3 payload ({ form, version: 3, answers }) stops here: never converted.
  if (body.formVersion !== AIVEX_FORM_VERSION) {
    return fail(`This registration must use AIVEX form v${AIVEX_FORM_VERSION}. Please reload the page.`, 'formVersion')
  }
  if (body.edition !== AIVEX_EDITION) {
    return fail(`Registrations are open for AIVEX edition ${AIVEX_EDITION} only. Please reload the page.`, 'edition')
  }
  const extra = unexpectedKey(body, [...V4_FIELDS.registration, HONEYPOT_FIELD], '')
  if (extra) return extra

  if (!isUuidV4(body.submissionId)) return fail('Invalid submission id. Please reload the page.', 'submissionId')

  const team = readTeam(body.team)
  if (!team.ok) return team
  const activityOfficial = readActivityOfficial(body.activityOfficial)
  if (!activityOfficial.ok) return activityOfficial
  const delegationHead = readPerson(body.delegationHead, 'delegationHead', 'Head of delegation', identityCardField('delegationHead'))
  if (!delegationHead.ok) return delegationHead
  const driver = readPerson(body.driver, 'driver', 'Driver', identityCardField('driver'))
  if (!driver.ok) return driver
  const students = readStudents(body.students)
  if (!students.ok) return students
  if (body.consent !== true) return fail('Please confirm the registration statement before submitting.', 'consent')

  return pass({
    submissionId: body.submissionId.toLowerCase(),
    edition: AIVEX_EDITION,
    formVersion: AIVEX_FORM_VERSION,
    team: team.value,
    activityOfficial: activityOfficial.value,
    delegationHead: delegationHead.value,
    driver: driver.value,
    students: students.value,
    consent: true,
  })
}

// --- Response contract ----------------------------------------------------

// 201 new registration, 200 idempotent replay of the same submissionId,
// 400 validation (with `field`), 409 conflict or still processing, 413/415
// card or identity card file, 429 rate limit, 500 server error. Bodies never carry SQL,
// Supabase, Storage paths or stack details.
export const registrationResponsesV4 = Object.freeze({
  created: (reference) => ({ status: 201, body: { success: true, reference } }),
  replayed: (reference) => ({ status: 200, body: { success: true, reference, alreadyProcessed: true } }),
  failed: (status, message, field) => ({ status, body: { success: false, message, ...(field ? { field } : {}) } }),
})

// --- Frontend contract ----------------------------------------------------

// UUID v4. crypto.randomUUID() only exists in secure contexts (HTTPS,
// localhost); getRandomValues() also covers plain-HTTP previews on a LAN.
export function createSubmissionId(cryptoSource = globalThis.crypto) {
  if (typeof cryptoSource?.randomUUID === 'function') return cryptoSource.randomUUID()
  const bytes = cryptoSource.getRandomValues(new Uint8Array(16))
  bytes[6] = (bytes[6] & 0x0f) | 0x40
  bytes[8] = (bytes[8] & 0x3f) | 0x80
  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join('')
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`
}

// Three fixed records (student-1..3): the ids never change, nothing is
// added or removed.
export const createStudentStateV4 = (position) => ({
  id: `student-${position}`,
  position,
  fullName: '',
  phone: '',
  bacYear: '',
  rfid: '',
  studentCard: null,
})

// Initial form state: always three student records, no add/remove. The
// submissionId is created once and must survive retries and reloads of the
// same attempt; it is renewed only after a confirmed success or a reset.
export function createRegistrationStateV4({ submissionId = createSubmissionId() } = {}) {
  return {
    submissionId,
    team: { name: '', wilaya: '', institution: '', customInstitution: '' },
    activityOfficial: { role: '', fullName: '', email: '', phone: '' },
    // idCard: the picked File (or null). Like studentCard, it never enters a draft.
    delegationHead: { fullName: '', phone: '', rfid: '', idCard: null },
    driver: { fullName: '', phone: '', rfid: '', idCard: null },
    students: STUDENT_POSITIONS.map(createStudentStateV4),
    consent: false,
  }
}

// Canonical payload (the `payload` multipart part) from the form state. No
// reference, status or date: those belong to the server.
export function buildRegistrationPayloadV4(state) {
  const { team, activityOfficial, delegationHead, driver, students } = state
  const wilaya = findWilaya(team.wilaya)
  const custom = team.institution === OTHER_INSTITUTION_ID
  const listed = custom ? null : findInstitution(team.wilaya, team.institution)
  const person = (record, subject) => ({
    fullName: normalizePersonName(record.fullName),
    phone: normalizePhone(record.phone),
    rfid: normalizeRfid(record.rfid),
    idCard: identityCardField(subject),
  })

  return {
    submissionId: state.submissionId,
    edition: AIVEX_EDITION,
    formVersion: AIVEX_FORM_VERSION,
    team: {
      name: normalizeText(team.name),
      wilaya: { code: wilaya?.code ?? '', name: wilaya?.name ?? '' },
      institution: custom
        ? { id: OTHER_INSTITUTION_ID, name: normalizeText(team.customInstitution), custom: true }
        : { id: listed?.id ?? '', name: listed?.name ?? '', custom: false },
    },
    activityOfficial: {
      role: activityOfficial.role,
      fullName: normalizePersonName(activityOfficial.fullName),
      email: normalizeEmail(activityOfficial.email),
      phone: normalizePhone(activityOfficial.phone),
    },
    delegationHead: person(delegationHead, 'delegationHead'),
    driver: person(driver, 'driver'),
    students: students.map((student) => ({
      position: student.position,
      fullName: normalizePersonName(student.fullName),
      phone: normalizePhone(student.phone),
      bacYear: normalizeBacYear(student.bacYear),
      rfid: normalizeRfid(student.rfid),
      studentCard: studentCardField(student.position),
    })),
    consent: state.consent === true,
  }
}
