// AIVEX registration — Data Contract V4 (canonical).
//
// One module shared by the browser form, the API and the tests: versions,
// enums, limits, pure normalisers and field rules, the V4 payload validator,
// the frontend state/payload builders, the student card policy and the
// Storage path rule. See docs/aivex-data-contract-v4.md.
//
// A registration carries two classes of data:
//   OFFICIAL DATA               -> PostgreSQL, Word/PDF, admin views
//   INTERNAL VERIFICATION DATA  -> the three student card photos: private
//                                  Storage bucket, path/mime/size in
//                                  PostgreSQL, never printed, never public.
//
// Pure: no React, window, document, Supabase, process.env or network, so it
// runs as is in Vite, in a Vercel Function and under `node --test`. The form
// runs these rules for UX; the API always re-runs them and is the authority.
// The public reference is generated by the API only (api/_lib/aivex-reference.js).

import { OTHER_INSTITUTION_ID, findInstitution, findWilaya } from '../../src/data/algeriaHigherEducation.js'

const frozen = (list) => Object.freeze([...list])

// --- Versions -----------------------------------------------------------

export const AIVEX_FORM_VERSION = 4
// The edition registrations are open for. The browser echoes it and the API
// refuses any other value: a stale page can never file into another edition.
export const AIVEX_EDITION = 2
// Official rule: a team is EXACTLY three students.
export const AIVEX_STUDENT_COUNT = 3
export const STUDENT_POSITIONS = frozen(Array.from({ length: AIVEX_STUDENT_COUNT }, (_, index) => index + 1))

// --- Enums (values stored in the database, never UI labels) --------------

export const ACTIVITY_OFFICIAL_ROLES = frozen(['sub_director_activities', 'activities_officer'])

export const REGISTRATION_STATUSES = frozen(['submitted', 'under_review', 'approved', 'rejected', 'cancelled'])
export const DEFAULT_REGISTRATION_STATUS = 'submitted'

// inscription -> Word/PDF -> print -> signature + stamp -> upload -> admin check
export const DOCUMENT_STATUSES = frozen([
  'not_generated',
  'generating',
  'awaiting_signature',
  'signed_document_uploaded',
  'under_review',
  'changes_required',
  'validated',
  'generation_failed',
  'expired',
])
export const DEFAULT_DOCUMENT_STATUS = 'not_generated'

// --- Payload shape --------------------------------------------------------

// Every object of the payload is closed: a key outside these lists is
// refused with its path, never silently dropped.
export const V4_FIELDS = Object.freeze({
  registration: frozen([
    'submissionId', 'edition', 'formVersion', 'team', 'activityOfficial', 'delegationHead', 'driver', 'students', 'consent',
  ]),
  team: frozen(['name', 'wilaya', 'institution']),
  wilaya: frozen(['code', 'name']),
  institution: frozen(['id', 'name', 'custom']),
  activityOfficial: frozen(['role', 'fullName', 'email', 'phone']),
  person: frozen(['fullName', 'phone', 'rfid']),
  student: frozen(['position', 'fullName', 'phone', 'bacYear', 'rfid', 'studentCard']),
})

// Owned by the server: sending one of them is a contract violation.
export const SERVER_AUTHORITATIVE_FIELDS = frozen([
  'id', 'reference', 'status', 'registrationStatus', 'documentStatus', 'currentFormRevision', 'templateVersion',
  'submittedAt', 'source', 'createdAt', 'updatedAt',
])

// Form v3 vocabulary: refused wherever it appears, with an explicit message.
export const LEGACY_V3_FIELDS = frozen([
  'form', 'version', 'answers', 'nationalId', 'registrationNumber', 'studyLevel', 'leader', 'isLeader', 'member',
])

// Anti-bot field. The handler answers a neutral success before validation
// when it is filled, so the validator only tolerates the key (top level).
const HONEYPOT_FIELD = 'website'

export const DATA_CLASSES = Object.freeze({
  internalVerification: frozen(['students[].studentCard']),
})

// --- Student card (INTERNAL VERIFICATION DATA) ---------------------------

export const studentCardField = (position) => `studentCard_${position}`
export const STUDENT_CARD_FIELDS = frozen(STUDENT_POSITIONS.map(studentCardField))
export const STUDENT_CARD_FIELD_PATTERN = new RegExp(`^studentCard_[1-${AIVEX_STUDENT_COUNT}]$`)

export const STUDENT_CARD_POLICY = Object.freeze({
  classification: 'internal_verification',
  required: true,
  printable: false,
  bucket: 'aivex-student-cards',
  publicBucket: false,
  maxBytes: 5 * 1024 * 1024,
  // Images only: the organisers ask for a photo of the card. PDF stays out
  // until they explicitly need it (open decision).
  types: Object.freeze({
    'image/jpeg': Object.freeze({ extension: 'jpg', extensions: frozen(['jpg', 'jpeg']), label: 'JPG' }),
    'image/png': Object.freeze({ extension: 'png', extensions: frozen(['png']), label: 'PNG' }),
    'image/webp': Object.freeze({ extension: 'webp', extensions: frozen(['webp']), label: 'WEBP' }),
  }),
  mimeAliases: Object.freeze({ 'image/jpg': 'image/jpeg', 'image/pjpeg': 'image/jpeg' }),
})

export const canonicalCardMime = (mime) => {
  const type = String(mime || '').toLowerCase()
  return STUDENT_CARD_POLICY.mimeAliases[type] || type
}

// The checks the form runs on a picked file and the API runs again on the
// received part (from the declared type and the real byte count). Returns ''
// or 'missing' | 'type' | 'empty' | 'size'. The API then also reads the
// file's magic bytes, which a browser cannot do reliably.
export function studentCardFileIssue(file) {
  if (!file) return 'missing'
  if (!STUDENT_CARD_POLICY.types[canonicalCardMime(file.type)]) return 'type'
  if (!(file.size > 0)) return 'empty'
  if (file.size > STUDENT_CARD_POLICY.maxBytes) return 'size'
  return ''
}

// Multipart file name for a card: derived from the position and type, so the
// applicant's own file name (which may contain a name) never leaves the device.
export function studentCardUploadName(position, mime) {
  const type = STUDENT_CARD_POLICY.types[canonicalCardMime(mime)]
  return type ? `${studentCardField(position)}.${type.extension}` : studentCardField(position)
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const UUID_V4_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

export const isUuidV4 = (value) => typeof value === 'string' && UUID_V4_RE.test(value)

// Deterministic private path inside the bucket, without personal data:
// edition-{edition}/{registrationId}/student-{position}.{ext}. Never a public URL.
export function studentCardStoragePath(registrationId, position, mime, edition = AIVEX_EDITION) {
  const type = STUDENT_CARD_POLICY.types[mime]
  if (typeof registrationId !== 'string' || !UUID_RE.test(registrationId)
    || !STUDENT_POSITIONS.includes(position) || !type || !Number.isInteger(edition) || edition < 1) {
    throw new TypeError('Invalid student card storage path input.')
  }
  return `edition-${edition}/${registrationId.toLowerCase()}/student-${position}.${type.extension}`
}

// --- Limits -------------------------------------------------------------

export const LIMITS = Object.freeze({
  teamName: frozen([2, 120]),
  customInstitution: frozen([3, 180]),
  fullName: frozen([3, 120]),
  email: 254,
  phoneInput: 40,
  // Technical bounds only: no RFID format has been confirmed by the organisers.
  rfid: frozen([1, 64]),
  source: 500,
  bacYearMin: 1990,
  bacYearAhead: 1,
})

// --- Normalisers (pure, identical in the browser and on the server) -------

const CONTROL_CHARS = /\p{Cc}/gu

// Trimmed, NFC, control characters and runs of whitespace folded to one space.
export const normalizeText = (value) => (typeof value === 'string'
  ? value.normalize('NFC').replace(CONTROL_CHARS, ' ').replace(/\s+/g, ' ').trim()
  : '')

export const normalizeEmail = (value) => (typeof value === 'string' ? value.trim().toLowerCase() : '')

// Separators removed, optional leading '+' kept: '0555 12 34 56' -> '0555123456',
// '+213 555 12 34 56' -> '+213555123456'. Always a string, never a Number.
export const normalizePhone = (value) => (typeof value === 'string' ? value.trim().replace(/[\s().-]/g, '') : '')

// An RFID is an identifier, not a quantity: a string, trimmed, nothing else
// (leading zeros and case are kept as typed).
export const normalizeRfid = (value) => (typeof value === 'string' ? value.trim() : '')

// Form inputs give '2023'; the payload carries the integer 2023. Anything
// else ('BAC 2023', '2023/2024', 2023.5) becomes null and fails validation.
export function normalizeBacYear(value) {
  if (Number.isInteger(value)) return value
  if (typeof value === 'string' && /^\d{4}$/.test(value.trim())) return Number(value.trim())
  return null
}

// --- Field rules (shared by the form messages and the API validator) ------

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
const PHONE_RE = /^\+?\d{9,15}$/
const WILAYA_CODE_RE = /^(0[1-9]|[1-4][0-9]|5[0-8])$/

export const within = (text, [min, max]) => text.length >= min && text.length <= max
export const isValidEmail = (email) => email.length <= LIMITS.email && EMAIL_RE.test(email)
export const isValidRfid = (rfid) => rfid.length >= LIMITS.rfid[0] && rfid.length <= LIMITS.rfid[1]
  && !/\p{Cc}/u.test(rfid)

// Raw input (as typed) -> is it an acceptable phone number once normalised?
export const isValidPhoneInput = (value) => typeof value === 'string'
  && value.trim().length <= LIMITS.phoneInput && PHONE_RE.test(normalizePhone(value))

export const bacYearRange = (now = new Date()) => ({
  min: LIMITS.bacYearMin,
  max: now.getUTCFullYear() + LIMITS.bacYearAhead,
})

export function isValidBacYear(year, now = new Date()) {
  const { min, max } = bacYearRange(now)
  return Number.isInteger(year) && year >= min && year <= max
}

// Years offered by the form's select, most recent first. It stops at the
// current year: a university student already holds the BAC. The validator
// keeps the wider bacYearRange() tolerance.
export function bacYearChoices(now = new Date()) {
  const latest = now.getUTCFullYear()
  return Array.from({ length: latest - LIMITS.bacYearMin + 1 }, (_, index) => latest - index)
}

// --- Validator (pure: no database, no Storage, no network) ---------------

const isObject = (value) => value !== null && typeof value === 'object' && !Array.isArray(value)
const pass = (value) => ({ ok: true, value })
const fail = (message, field) => ({ ok: false, status: 400, message, ...(field ? { field } : {}) })
const at = (path, key) => (path ? `${path}.${key}` : key)

function unexpectedKey(record, allowed, path) {
  for (const key of Object.keys(record)) {
    if (allowed.includes(key)) continue
    if (SERVER_AUTHORITATIVE_FIELDS.includes(key)) {
      return fail(`"${key}" is assigned by the server and must not be sent.`, at(path, key))
    }
    if (LEGACY_V3_FIELDS.includes(key)) {
      return fail(`"${key}" belongs to the old registration form and is not accepted. Please reload the page.`, at(path, key))
    }
    return fail(`Unexpected field "${key}": it is not part of AIVEX form v${AIVEX_FORM_VERSION}.`, at(path, key))
  }
  return null
}

function readPhone(value, label, field) {
  return isValidPhoneInput(value) ? pass(normalizePhone(value)) : fail(`${label}: enter a valid phone number.`, field)
}

function readFullName(value, label, field) {
  const fullName = normalizeText(value)
  return within(fullName, LIMITS.fullName) ? pass(fullName) : fail(`${label}: enter the full name (3 to 120 characters).`, field)
}

function readRfid(value, label, field) {
  if (value === undefined || value === null) return fail(`${label}: the RFID is required.`, field)
  // A JSON number has already lost its leading zeros: strings only.
  if (typeof value !== 'string') return fail(`${label}: the RFID must be sent as text.`, field)
  const rfid = normalizeRfid(value)
  if (!rfid) return fail(`${label}: the RFID is required.`, field)
  return isValidRfid(rfid) ? pass(rfid) : fail(`${label}: enter the RFID (1 to 64 characters).`, field)
}

function readTeam(raw) {
  const path = 'team'
  if (!isObject(raw)) return fail('Team: invalid data.', path)
  const extra = unexpectedKey(raw, V4_FIELDS.team, path)
  if (extra) return extra

  const name = normalizeText(raw.name)
  if (!within(name, LIMITS.teamName)) return fail('Please enter a team name (2 to 120 characters).', `${path}.name`)

  if (!isObject(raw.wilaya)) return fail('Please choose a valid wilaya.', `${path}.wilaya`)
  const wilayaExtra = unexpectedKey(raw.wilaya, V4_FIELDS.wilaya, `${path}.wilaya`)
  if (wilayaExtra) return wilayaExtra
  const code = typeof raw.wilaya.code === 'string' ? raw.wilaya.code.trim() : ''
  const wilaya = WILAYA_CODE_RE.test(code) ? findWilaya(code) : null
  if (!wilaya) return fail('Please choose a valid wilaya.', `${path}.wilaya.code`)

  const rawInstitution = raw.institution
  if (!isObject(rawInstitution)) return fail('Please choose a university or institution.', `${path}.institution`)
  const institutionExtra = unexpectedKey(rawInstitution, V4_FIELDS.institution, `${path}.institution`)
  if (institutionExtra) return institutionExtra
  if (typeof rawInstitution.custom !== 'boolean') return fail('Invalid institution data.', `${path}.institution.custom`)
  const id = typeof rawInstitution.id === 'string' ? rawInstitution.id.trim() : ''

  let institution
  if (rawInstitution.custom) {
    if (id !== OTHER_INSTITUTION_ID) return fail(`A custom institution must use the id "${OTHER_INSTITUTION_ID}".`, `${path}.institution.id`)
    const customName = normalizeText(rawInstitution.name)
    if (!within(customName, LIMITS.customInstitution)) {
      return fail('Please enter the institution name (3 to 180 characters).', `${path}.institution.name`)
    }
    institution = { id: OTHER_INSTITUTION_ID, name: customName, custom: true }
  } else {
    const listed = id && id !== OTHER_INSTITUTION_ID ? findInstitution(wilaya.code, id) : null
    if (!listed) return fail('Please choose a university or institution from the selected wilaya.', `${path}.institution.id`)
    // Official label from the dataset, whatever the request claimed.
    institution = { id: listed.id, name: listed.name, custom: false }
  }

  // Snapshot: the labels stored with the registration are the dataset labels
  // of the day, so old registrations stay readable if the dataset changes.
  return pass({ name, wilaya: { code: wilaya.code, name: wilaya.name }, institution })
}

function readActivityOfficial(raw) {
  const path = 'activityOfficial'
  const label = 'Activity administration contact'
  if (!isObject(raw)) return fail(`${label}: invalid data.`, path)
  const extra = unexpectedKey(raw, V4_FIELDS.activityOfficial, path)
  if (extra) return extra

  const role = typeof raw.role === 'string' ? raw.role.trim() : ''
  if (!ACTIVITY_OFFICIAL_ROLES.includes(role)) return fail(`${label}: choose a role.`, `${path}.role`)

  const fullName = readFullName(raw.fullName, label, `${path}.fullName`)
  if (!fullName.ok) return fullName

  // Not unique: one official may register several teams (idempotency is
  // carried by submissionId, not by this address).
  const email = normalizeEmail(raw.email)
  if (!isValidEmail(email)) return fail(`${label}: enter a valid email address.`, `${path}.email`)

  const phone = readPhone(raw.phone, label, `${path}.phone`)
  if (!phone.ok) return phone

  return pass({ role, fullName: fullName.value, email, phone: phone.value })
}

// Head of delegation and driver: same record, identified by RFID (v4 never
// collects national ID numbers).
function readPerson(raw, path, label) {
  if (!isObject(raw)) return fail(`${label}: invalid data.`, path)
  const extra = unexpectedKey(raw, V4_FIELDS.person, path)
  if (extra) return extra

  const fullName = readFullName(raw.fullName, label, `${path}.fullName`)
  if (!fullName.ok) return fullName
  const phone = readPhone(raw.phone, label, `${path}.phone`)
  if (!phone.ok) return phone
  const rfid = readRfid(raw.rfid, label, `${path}.rfid`)
  if (!rfid.ok) return rfid

  return pass({ fullName: fullName.value, phone: phone.value, rfid: rfid.value })
}

function readStudents(raw, now) {
  const path = 'students'
  if (!Array.isArray(raw)) return fail('Invalid student list.', path)
  if (raw.length !== AIVEX_STUDENT_COUNT) return fail(`A team is exactly ${AIVEX_STUDENT_COUNT} students.`, path)

  const { min, max } = bacYearRange(now)
  const students = []
  const rfids = new Set()
  for (const [index, student] of raw.entries()) {
    const position = index + 1
    const base = `${path}[${index}]`
    const label = `Student ${position}`
    if (!isObject(student)) return fail(`${label}: invalid data.`, base)
    const extra = unexpectedKey(student, V4_FIELDS.student, base)
    if (extra) return extra

    if (student.position !== position) return fail(`${label}: the position must be ${position}.`, `${base}.position`)

    const fullName = readFullName(student.fullName, label, `${base}.fullName`)
    if (!fullName.ok) return fullName
    const phone = readPhone(student.phone, label, `${base}.phone`)
    if (!phone.ok) return phone

    // The payload carries an integer: '2023', 'BAC 2023' or '2023/2024' are refused.
    if (student.bacYear === undefined || student.bacYear === null || student.bacYear === '') {
      return fail(`${label}: the BAC year is required.`, `${base}.bacYear`)
    }
    if (!isValidBacYear(student.bacYear, now)) return fail(`${label}: enter the BAC year (${min} to ${max}).`, `${base}.bacYear`)

    const rfid = readRfid(student.rfid, label, `${base}.rfid`)
    if (!rfid.ok) return rfid
    if (rfids.has(rfid.value)) return fail(`${label}: each student needs their own RFID.`, `${base}.rfid`)
    rfids.add(rfid.value)

    // The JSON only names the multipart part; the bytes travel separately.
    const cardField = studentCardField(position)
    if (student.studentCard !== cardField) return fail(`${label}: the student card must be sent as "${cardField}".`, `${base}.studentCard`)

    students.push({ position, fullName: fullName.value, phone: phone.value, bacYear: student.bacYear, rfid: rfid.value, studentCard: cardField })
  }
  return pass(students)
}

// Validates the canonical v4 payload (the `payload` multipart part). Returns
// { ok: true, value } with a clean, explicitly rebuilt structure — the only
// input the API maps to the database — or { ok: false, status: 400, message,
// field } where `field` is the payload path of the first problem.
export function validateRegistrationV4(body, { now = new Date() } = {}) {
  if (!isObject(body)) return fail('Invalid registration data.')
  // A v3 payload ({ form, version: 3, answers }) stops here: never converted.
  if (body.formVersion !== AIVEX_FORM_VERSION) {
    return fail(`This registration must use AIVEX form v${AIVEX_FORM_VERSION}. Please reload the page.`, 'formVersion')
  }
  if (body.edition !== AIVEX_EDITION) {
    return fail(`Registrations are open for AIVEX edition ${AIVEX_EDITION} only. Please reload the page.`, 'edition')
  }
  const extra = unexpectedKey(body, [...V4_FIELDS.registration, HONEYPOT_FIELD], '')
  if (extra) return extra

  if (!isUuidV4(body.submissionId)) return fail('Invalid submission id. Please reload the page.', 'submissionId')

  const team = readTeam(body.team)
  if (!team.ok) return team
  const activityOfficial = readActivityOfficial(body.activityOfficial)
  if (!activityOfficial.ok) return activityOfficial
  const delegationHead = readPerson(body.delegationHead, 'delegationHead', 'Head of delegation')
  if (!delegationHead.ok) return delegationHead
  const driver = readPerson(body.driver, 'driver', 'Driver')
  if (!driver.ok) return driver
  const students = readStudents(body.students, now)
  if (!students.ok) return students
  if (body.consent !== true) return fail('Please confirm the registration statement before submitting.', 'consent')

  return pass({
    submissionId: body.submissionId.toLowerCase(),
    edition: AIVEX_EDITION,
    formVersion: AIVEX_FORM_VERSION,
    team: team.value,
    activityOfficial: activityOfficial.value,
    delegationHead: delegationHead.value,
    driver: driver.value,
    students: students.value,
    consent: true,
  })
}

// --- Response contract ----------------------------------------------------

// 201 new registration, 200 idempotent replay of the same submissionId,
// 400 validation (with `field`), 409 conflict or still processing, 413/415
// card file, 429 rate limit, 500 server error. Bodies never carry SQL,
// Supabase, Storage paths or stack details.
export const registrationResponsesV4 = Object.freeze({
  created: (reference) => ({ status: 201, body: { success: true, reference } }),
  replayed: (reference) => ({ status: 200, body: { success: true, reference, alreadyProcessed: true } }),
  failed: (status, message, field) => ({ status, body: { success: false, message, ...(field ? { field } : {}) } }),
})

// --- Frontend contract ----------------------------------------------------

// UUID v4. crypto.randomUUID() only exists in secure contexts (HTTPS,
// localhost); getRandomValues() also covers plain-HTTP previews on a LAN.
export function createSubmissionId(cryptoSource = globalThis.crypto) {
  if (typeof cryptoSource?.randomUUID === 'function') return cryptoSource.randomUUID()
  const bytes = cryptoSource.getRandomValues(new Uint8Array(16))
  bytes[6] = (bytes[6] & 0x0f) | 0x40
  bytes[8] = (bytes[8] & 0x3f) | 0x80
  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join('')
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`
}

// Three fixed records (student-1..3): the ids never change, nothing is
// added or removed.
export const createStudentStateV4 = (position) => ({
  id: `student-${position}`,
  position,
  fullName: '',
  phone: '',
  bacYear: '',
  rfid: '',
  studentCard: null,
})

// Initial form state: always three student records, no add/remove. The
// submissionId is created once and must survive retries and reloads of the
// same attempt; it is renewed only after a confirmed success or a reset.
export function createRegistrationStateV4({ submissionId = createSubmissionId() } = {}) {
  return {
    submissionId,
    team: { name: '', wilaya: '', institution: '', customInstitution: '' },
    activityOfficial: { role: '', fullName: '', email: '', phone: '' },
    delegationHead: { fullName: '', phone: '', rfid: '' },
    driver: { fullName: '', phone: '', rfid: '' },
    students: STUDENT_POSITIONS.map(createStudentStateV4),
    consent: false,
  }
}

// Canonical payload (the `payload` multipart part) from the form state. No
// reference, status or date: those belong to the server.
export function buildRegistrationPayloadV4(state) {
  const { team, activityOfficial, delegationHead, driver, students } = state
  const wilaya = findWilaya(team.wilaya)
  const custom = team.institution === OTHER_INSTITUTION_ID
  const listed = custom ? null : findInstitution(team.wilaya, team.institution)
  const person = (record) => ({
    fullName: normalizeText(record.fullName),
    phone: normalizePhone(record.phone),
    rfid: normalizeRfid(record.rfid),
  })

  return {
    submissionId: state.submissionId,
    edition: AIVEX_EDITION,
    formVersion: AIVEX_FORM_VERSION,
    team: {
      name: normalizeText(team.name),
      wilaya: { code: wilaya?.code ?? '', name: wilaya?.name ?? '' },
      institution: custom
        ? { id: OTHER_INSTITUTION_ID, name: normalizeText(team.customInstitution), custom: true }
        : { id: listed?.id ?? '', name: listed?.name ?? '', custom: false },
    },
    activityOfficial: {
      role: activityOfficial.role,
      fullName: normalizeText(activityOfficial.fullName),
      email: normalizeEmail(activityOfficial.email),
      phone: normalizePhone(activityOfficial.phone),
    },
    delegationHead: person(delegationHead),
    driver: person(driver),
    students: students.map((student) => ({
      position: student.position,
      fullName: normalizeText(student.fullName),
      phone: normalizePhone(student.phone),
      bacYear: normalizeBacYear(student.bacYear),
      rfid: normalizeRfid(student.rfid),
      studentCard: studentCardField(student.position),
    })),
    consent: state.consent === true,
  }
}
